name: CI

on: [pull_request]

env:
  flutter_version: "3.0.5"

jobs:

  setup:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    strategy:
      matrix:
        os: [windows-2022]
        include:
          - os: windows-2022
            flutter_path: C:\hostedtoolcache\windows\flutter
      # Disable fail-fast; we want results from all OSes even if one fails.
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Flutter env
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter_version }}
          channel: 'stable'

      - name: Flutter Windows
        if: startsWith(matrix.os, 'windows')
        run: |
          flutter config --enable-windows-desktop
          flutter build windows

      - name: Cache Flutter
        uses: actions/cache@v3
        with:
          path: ${{ matrix.flutter_path }}
          key: ${{ runner.os }}-flutter

      - name: Flutter Test
        run: flutter test
